Input-group , dropdowns and form-check
dynamic-framework/dynamic-ui pull request #573
Opened 2024-03-01 16:55 UTC by lnazarit

input-group , dropdowns and form-check

2024-03-01 17:07 UTC, abe-modyo requested changes

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_+import.scss
>  $input-btn-focus-blur: 0 !default;
por acá dejemos la definición que propone bootstrap que es la que va a tomar por default 

```suggestion
$input-btn-focus-blur: 0 !default;
$input-btn-focus-box-shadow: $focus-ring-box-shadow !default;
```

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_border.scss
> +$border-radius-xxl: 2rem !default;
parece que no coinciden con los de figma, 

<img width="725" alt="image" src="https://github.com/dynamic-framework/dynamic-ui/assets/102051289/02a316e2-b2fe-499f-b35e-e3df3ceceed9">

tampoco los que teníamos definidos nosotros (figma cambia mucho).

creería que medium en figma es el normal, partiendo de ahí supondría:

$border-radius: .5rem;
$border-radius-sm: .25rem;
$border-radius-lg: 1rem;

los demás sería buscar un patrón y seguirlo.

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_dropdowns.scss
> +$dropdown-link-hover-bg: rgb(var(--#{$prefix}gray-100-rgb)) !default;
```suggestion
$dropdown-link-hover-bg: rgb(var(--#{$prefix}gray-100-rgb)) !default;
$dropdown-link-hover-color: $dropdown-link-color !default;
```
si no le dejas un valor tomará la definición de bootstrap, que es la misma 

tratamos de dejar todas las variables que ofrece bootstrap escritas acá igual con !default; así no las cambiemos, nos deja ver rápidamente que variables tenemos disponibles.

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_dropdowns.scss
> +}
este archivo solo tiene variables, esto iría en 🤔 base/_dropdown.scss

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_forms.scss
> +
por acá lo mismo que comentaba arriba de la variable, dejemos la definición que propone bootstrap que es la que igual va a tomar el ouput si no hay variable :) 

```suggestion
$input-box-shadow: var(--#{$prefix}box-shadow-inset) !default; // unused
```

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_forms.scss
> +$enable-shadows: false !default;
esta definición iría en el archivo de opciones 

libraries/dynamic-ui-react/src/style/abstracts/variables/_options.scss

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_forms.scss
> +$input-box-shadow: none !default;
esta definición iría arriba en donde borraste la definición, es el mismo orden en el que bootstrap tiene sus variables generalmente. :) linea 50.

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_forms.scss
>  $form-range-track-border-radius: 1rem !default;
```suggestion
$form-range-track-border-radius: 1rem !default;
$form-range-track-box-shadow: var(--#{$prefix}box-shadow-inset) !default;
```

por acá habría que dejar la definición que propone bootstrap, como comento arriba.

2024-03-01 17:07 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/base/_form-check.scss
> +  min-height: 1.7rem;
equivaldría a 27.2px :), tratamos de no dejar valores que se puedan sentir arbitrarios, en este caso ideal que quede expresado porque es 1.7rem, algo como si estas usando el borde + el padding o alguna expresión que demuestre como se llega a ese 1.7rem que sirva de justificación para nosotros mismos en el futuro.

2024-03-01 17:36 UTC, abe-modyo commented
los inputs quedaron con un border radius distinto al de figma 

fimga: 
<img width="1259" alt="image" src="https://github.com/dynamic-framework/dynamic-ui/assets/102051289/79d2c935-c3e5-4ee2-b6ba-0d030abcca26">

storybook en la rama:

<img width="1406" alt="image" src="https://github.com/dynamic-framework/dynamic-ui/assets/102051289/f0635ee1-6415-45ed-aa33-0a6910115648">

imagino que ajustando los bordes como te comenté arriba se arreglaría.

2024-03-01 17:44 UTC, abe-modyo commented
El paginador ahora no se ve rounded 🤔, aunque las variables del paginador no cambiaron, así que imagino que es por el cambio en las globales, creo que en este caso no se arreglará aún cambiando las variables gloables jaja, creo que es necesario ajustar las del paginador directamente apuntando a pill 

<img width="1360" alt="image" src="https://github.com/dynamic-framework/dynamic-ui/assets/102051289/533dc2c2-9637-4ee6-9c10-312b679f11fa">

2024-03-01 18:09 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_border.scss
> +$border-radius-xxl: 2rem !default;
```suggestion
$border-radius: 1rem;
$border-radius-sm: .5rem;
$border-radius-lg: 1.5rem;
$border-radius-xl: 2rem;
$border-radius-xxl: 2.5rem;
```

2024-03-02 02:09 UTC, abe-modyo commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_forms.scss
> +$form-check-size-multiplier: 1.5 !default;
después de revisar como funciona bootstrap, se me ocurrió devolver la variable $form-check-input-width a su valor original, 1em y crear una variable para multiplicar todos los cálculos que se realizan y así escalar el check de bootstrap, funcionó bien :) 

1.5 que es lo esperado @lnazarit

2024-03-04 14:16 UTC, efbarong approved these changes

2024-03-04 14:21 UTC, abe-modyo approved these changes

2024-03-04 14:58 UTC, johannrp27 approved these changes

2024-03-04 14:58 UTC, johannrp27 commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_forms.scss
> +$input-padding-x-lg: 1rem !default;
Spacers (?

2024-03-04 14:58 UTC, johannrp27 commented on libraries/dynamic-ui-react/src/style/abstracts/variables/_navs.scss
> +$nav-link-padding-y: .5rem !default;
Spacers(?

2024-03-04 15:08 UTC, merged