docs(DInputMask): add react-input/mask usage through useState
dynamic-framework/dynamic-ui pull request #650
Opened 2024-05-15 19:24 UTC by johannrp27

2024-05-16 16:22 UTC, efbarong submitted a review, later dismissed

2024-05-17 14:18 UTC, abe-modyo approved these changes

2024-05-17 14:18 UTC, abe-modyo requested changes
Como hacemos con el modal o el offcanvas sería ideal dejar el componente creado aparte y renderizarlo en un <Canva dentro para que se vea el ejemplo de código funcionando.

2024-05-17 14:19 UTC, abe-modyo commented on libraries/dynamic-ui-react/stories/components/DInputMask.mdx
> +  const baseMask = useMemo(() => '_ ____ ____', []);
como no tiene dependencias mejor que sea una constante fuera del componente :)

2024-05-20 13:21 UTC, abe-modyo approved these changes

2024-05-20 14:53 UTC, merged